mysql:
  image: mysql
  container_name: database
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: laravel
    MYSQL_ROOT_PASSWORD: root

php:
  image: php:fpm-alpine
  container_name: php
  volumes:
    - .:/var/www/laradock
  entrypoint:
    - php-fpm

nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8080:80